app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('restaurants', 'RestaurantsController')->middleware('can:access,App\Restaurants');

Route::resource('goods', 'GoodsController')->middleware('can:access,App\Goods');

Route::resource('managers', 'ManagersController', ['only' => 
        ['create', 'show', 'store', 'destroy']])
        ->middleware('can:access,App\Restaurants');

Route::resource('categories', 'CategoriesController', ['only' => 
        ['index', 'create', 'store', 'destroy']])
        ->middleware('can:access,App\Restaurants');

Route::resource('couriers', 'CouriersController', ['only' => 
        ['index', 'create', 'store', 'destroy']])
        ->middleware('can:access,App\Restaurants');

Route::get('/', 'FrontendController@restaurants_list')->name('index');
Route::get('/restaurant/{restaurant}', 'FrontendController@restaurant')->name('restaurant');

Route::post('/create-order', 'FrontendController@create_order');
Route::get('/order-confirmation', 'FrontendController@order_confirmation')->name('order_confirmation');
Route::get('/order-cancel/{id}', 'FrontendController@order_cancel')->name('order_cancel');
Route::get('/opened-orders', 'OrdersController@opened_orders_list')->name('opened_orders');

Route::resource('orders', 'OrdersController', ['only' => 
['show', 'store', 'destroy']]);

Route::post('order-completing/{order}', 'OrdersController@complete')->name('order_complete');
Route::post('/courier/attach-order/', 'OrdersController@couriers_attach_order')->name('couriers_attach_order');
Route::get('/courier/orders/', 'OrdersController@couriers_orders_list')->name('couriers_orders_list');

Route::post('/accounts/{id}', 'AccountController@update')->name('accounts_update');

Route::get('rate/{token}', 'RateController@show')->name('rate');
Route::post('rate', 'RateController@store')->name('add_rate');

app/app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Restaurants;
use App\Goods;
use App\OrdersOnQueue;
use App\Accounts;

class FrontendController extends Controller
{
    public function restaurants_list(Request $request) 
    {
        if ($request->has('name')) {
            $search = (string)$request['name'];
            return view('frontend.index', ['restaurants' => Restaurants::where('name_lower', 'like', '%' . mb_strtolower($search) . '%')
                ->paginate(6)
                ->appends(request()->query()), 'name' => $search]);
        }
        return view('frontend.index', ['restaurants' => Restaurants::paginate(6)
            ->appends(request()
            ->query()), 'name' => NULL]);   
    }

    public function restaurant($restaurant)
    {
        $restaurant = Restaurants::where('name', '=', $restaurant)->first();
        $goods = Goods::where('restaurant_id', '=', $restaurant->id)->paginate(6);

        return view('frontend.restaurant', [
            'restaurant' =>  $restaurant,
            'goods' =>  $goods,
        ]);
    }

    public function create_order(Request $request) {
        return redirect(route('order_confirmation', ['order_info' => $request->input()]));
    }

    public function order_confirmation(Request $request) {
        try {
            $order_input = $request->input('order_info');
            $restaurant = NULL;
            if (!$order_input) {
                abort('500');
            }

            $restaurant_input = NULL;
            $goods_input = [];
            $goods = [];
            $total = 0;
            $address = (Auth::check())?Auth::user()->account->address:'';

            foreach ($order_input as $key => $value) {
                if (array_key_exists('restaurant', $value)) {
                    $restaurant_input = $value['restaurant'];
                }
                if (array_key_exists('address', $value)) {
                    $address = $value['address'];
                }
                if (array_key_exists('goods', $value)) {
                    $goods_input = $value['goods'];
                }
            }

            $restaurant = Restaurants::where('name', '=', $restaurant_input)->first();
            
            foreach ($goods_input as $key => $order_good) {
                $added = false;
                foreach ($restaurant->goods as $rest_key => $good) {
                    if ($good->name == $order_good['name']) {
                        array_push($goods, [$good, (int)$order_good['amount']]);
                        $total += (int)$order_good['amount'] * $good->price;
                        $added = true;
                        break;
                    }
                }
                if (!$added) {
                    abort('500');
                }
            }

            $order = OrdersOnQueue::create([
                'goods' => json_encode($goods),
                'restaurant_id' => $restaurant->id,
                'total' => $total,
            ]);

            return view('frontend.order_confirmation', [
                'goods' => $goods,
                'restaurant' => $restaurant,
                'address' => $address,
                'total' => $total,
                'order' => $order,
            ]);

        } catch (Exception $e) {
            abort('500');
        }

    }

    public function order_cancel($id) {
        $obj = OrdersOnQueue::find($id);
        if ($obj)
            $obj->delete();
        return redirect('/');
    }
}

app/resources/views/frontend/index.blade.php
@extends('layouts.frontend')

@section('content')
<div class="container">
    <section class="promo">
        <h1 class="promo-title">Онлайн-сервис<br>доставки еды на дом</h1>
        <p class="promo-text">Блюда из любимого ресторана привезет курьер в перчатках, маске и с антисептиком</p>
    </section>

    <section class="restaurants">
        @auth
            @if(Auth::user()->account->role->name == 'admin')
                <div class="add-position"><a href="{{route('restaurants.create')}}">Добавить ресторан</a></div>
            @endif
        @endauth
        <div class="section-heading">
            <h2 class="section-title">Рестораны</h2>
            <form method='GET' action='' class="restaurant-search-form">
                <input class="input input-search" placeholder="Поиск ресторанов" name="name" value="{{ $name }}" autocomplete="{{ $name }}"/>
            </form>
        </div>
        <div class="cards">

            @foreach($restaurants as $restaurant)

            <a href="{{route('restaurant', $restaurant->name)}}" class="card">
                <img class="card-image" src="{{ $restaurant->image->path }}" alt="">
                <div class="card-text">
                    <div class="card-heading">
                        <h3 class="card-title"> {{ $restaurant->name }} </h3>
                        <span class="card-tag tag">
                        @php
                        $amount = 0;
                        $time_in_seconds = 0;
                        foreach ($restaurant->orders as $order) {
                            if ($order->status->name == 'Завершен') {
                                $amount += 1;
                                $time_in_seconds += (int)(strtotime($order->updated_at) - strtotime($order->created_at));
                                // echo $time_in_seconds . '<br>';
                            }
                        }
                        if ($amount > 0) {
                            echo round($time_in_seconds / $amount / 60);
                        } else {
                            echo '-' ;
                        }
                        @endphp
                        мин
                        </span>
                    </div>
                    <!-- /.card-heading -->
                    <div class="card-info">

                        @if($restaurant->rates->first())
                        <div class="rating">
                        <img src="{{asset('/images/rating.svg')}}" alt="">
                         @php
                            $rates = $restaurant->rates;
                            $sum = 0;
                            $amount = 0;
                            foreach($rates as $rate) {
                                $sum += (int)$rate->rate;
                                $amount += 1;
                            }
                            echo round($sum / $amount, 2);
                         @endphp
                        </div>
                        @endif
                        
                        @if(!$restaurant->goods->isEmpty())
                            @php
                                $prices = $restaurant->goods->filter(function ($item) {
                                    return !is_null($item->price);
                                });
                                $min_price = $prices->min('price');
                                $min_price = 'От ' . $min_price . ' ₽';
                            @endphp
                        @else 
                            @php
                            $min_price = "Нет позиций";
                            @endphp
                        @endif
                        <div class="price">{{$min_price}}</div>
                        <div class="category"> {{ $restaurant->category->name }} </div>
                    </div>
                    <!-- /.card-info -->
                </div>
            </a>
            <!-- /.card -->

            @endforeach

        </div>
        <div class="pagination-container">
            {{ $restaurants->links("pagination::bootstrap-4") }}
        </div>
    </section>
</div>
@endsection

app/resources/views/frontend/order_confirmation.blade.php
@extends('layouts.frontend')

@section('content')
<div class="container">
    <form action="{{route('orders.store')}}" method="POST" class="form-confirmation">

        {{csrf_field()}}
        <div class="modal-dialog">
            <div class="modal-header">
                <h3 class="modal-title">Заказ</h3>
            </div>
            <div>
                <h3>Доставка из {{$restaurant->name}}:</h3>
            </div>

            <!-- /.modal-header -->
            <div class="modal-body">
                @foreach($goods as $position)
                    <div class="food-row food-row-order-confirmation">
                        <span class="food-name">{{$position[0]['name']}}</span>
                        <strong class="food-price">{{$position[0]['price']}} ₽</strong>
                        <div class="food-counter">
                            <span class="counter">Количество: {{$position[1]}}</span>
                        </div>
                    </div>
                @endforeach
            </div>

            <div>
                <h3>Контактные данные:</h3>
            </div>
            <div class="modal-body">
                <div class="form-confirmation">
                    <span>ФИО:</span>
                    <div style="margin-bottom: 12px">
                        <input type="text" class="input input-fio" name="fio" @auth value="{{Auth::user()->account->FIO}}" @endauth required>
                    </div> 

                    <span>Email:</span>
                    <div style="margin-bottom: 12px;">
                        <input type="email" class="input input-email" name="email" @auth value="{{Auth::user()->email}}" @endauth required>
                    </div> 

                    <span>Телефон:</span>
                    <div style="margin-bottom: 12px;">
                        <input type="tel" class="input input-phone" name="tel" @auth value="{{Auth::user()->account->phone}}" @endauth required>
                    </div> 

                    <span>Адрес доставки:</span>
                    <div>
                        <input type="text" class="input input-address-delivery" name="address" @auth value="{{Auth::user()->account->address}}" @endauth required>
                    </div> 
                </div>
            </div>
            <input type="hidden" value="{{$order->id}}" name="order_on_queue">
            <!-- /.modal-body -->
            <div class="modal-footer">
                <span class="modal-price-tag order-total">{{$total}} ₽</span>
                <div class="footer-buttons">
                    <button type="submit" class="button button-primary">Оформить заказ</button>
                    <a class="button" href="{{route('order_cancel', $order->id)}}">Отмена</a>
                </div>
            </div>
            <!-- /.modal-footer -->
        </div>

    </form>

</div>

@endsection

app/resources/views/frontend/restaurant.blade.php
@extends('layouts.frontend')

@section('content')
<div class="container">

    <section class="restaurants">
        <div class="section-heading">
            <h2 class="section-title restaurant-name">{{ $restaurant->name }}</h2>
                @if($restaurant->rates->first())
                        <div class="rating">
                        <img src="{{asset('/images/rating.svg')}}" alt="">
                         @php
                            $rates = $restaurant->rates;
                            $sum = 0;
                            $amount = 0;
                            foreach($rates as $rate) {
                                $sum += (int)$rate->rate;
                                $amount += 1;
                            }
                            echo round($sum / $amount, 2);
                         @endphp
                        </div>
                        @endif
                @if(!$restaurant->goods->isEmpty())
                @php
                    $prices = $restaurant->goods->filter(function ($item) {
                        return !is_null($item->price);
                    });
                    $min_price = $prices->min('price');
                    $min_price = 'От ' . $min_price . ' ₽';
                @endphp
            @else 
                @php
                $min_price = "Нет позиций";
                @endphp
            @endif
            <div class="price">{{$min_price}}</div>
            <div class="category">{{ $restaurant->category->name }}</div>
            @auth
                @if(Auth::user()->account->role->name == 'manager')
                    @if(Auth::user()->account->manager->restaurant->id === $restaurant->id)
                        <div class="add-position"><a href="{{route('goods.create', 'restaurant='.$restaurant->name)}}">Добавить позицию</a></div>
                    @endif
                @elseif(Auth::user()->account->role->name == 'admin')
                <div class="add-position"><a href="{{route('restaurants.show', $restaurant->id)}}">Редактировать ресторан</a></div>
                @endif
            @endauth
        </div>
        <div class="cards">
            @foreach($goods as $good)
                <div class="card">
                    <img class="card-image" src="{{ $good->image->path }}" alt="">
                    <div class="card-text card-text-good">
                        <div class="card-heading">
                            <h3 class="card-title card-title-reg">{{ $good->name }}</h3>
                            @auth
                                @if(Auth::user()->account->role->name == 'manager')
                                    @if(Auth::user()->account->manager->restaurant->id === $restaurant->id)
                                    <div class="add-position"><a href="{{route('goods.edit', $good->id)}}">Редактировать</a></div>
                                    @endif
                                @endif
                            @endauth
                        </div>
                        <!-- /.card-heading -->
                        <div class="restaurant-card-info">
                            <div class="ingredients">{{ $good->description }}</div>
                        </div>
                        <!-- /.card-info -->
                        <div class="card-buttons">
                            <button class="button button-primary add-to-busket-btn" name="{{$good->name}}" value="{{$good->price}}">
                                <span class="button-card-text">В корзину</span>
                                <img src="{{ asset('images/shopping-cart2.svg') }}" alt="shopping-cart" class="button-cart-image">
                            </button>
                            <div class="card-price-bold"><strong>{{ $good->price }}₽</strong></div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            @endforeach

        </div>

        <div class="pagination-container">
            {{ $goods->links("pagination::bootstrap-4") }}
        </div>
    </section>
</div>
@endsection