app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('restaurants', 'RestaurantsController')->middleware('can:access,App\Restaurants');

Route::resource('goods', 'GoodsController')->middleware('can:access,App\Goods');

Route::resource('managers', 'ManagersController', ['only' => 
        ['create', 'show', 'store', 'destroy']])
        ->middleware('can:access,App\Restaurants');

Route::resource('categories', 'CategoriesController', ['only' => 
        ['index', 'create', 'store', 'destroy']])
        ->middleware('can:access,App\Restaurants');

Route::resource('couriers', 'CouriersController', ['only' => 
        ['index', 'create', 'store', 'destroy']])
        ->middleware('can:access,App\Restaurants');

Route::get('/', 'FrontendController@restaurants_list')->name('index');
Route::get('/restaurant/{restaurant}', 'FrontendController@restaurant')->name('restaurant');

Route::post('/create-order', 'FrontendController@create_order');
Route::get('/order-confirmation', 'FrontendController@order_confirmation')->name('order_confirmation');
Route::get('/order-cancel/{id}', 'FrontendController@order_cancel')->name('order_cancel');
Route::get('/opened-orders', 'OrdersController@opened_orders_list')->name('opened_orders');

Route::resource('orders', 'OrdersController', ['only' => 
['show', 'store', 'destroy']]);

Route::post('order-completing/{order}', 'OrdersController@complete')->name('order_complete');
Route::post('/courier/attach-order/', 'OrdersController@couriers_attach_order')->name('couriers_attach_order');
Route::get('/courier/orders/', 'OrdersController@couriers_orders_list')->name('couriers_orders_list');

Route::post('/accounts/{id}', 'AccountController@update')->name('accounts_update');

Route::get('rate/{token}', 'RateController@show')->name('rate');
Route::post('rate', 'RateController@store')->name('add_rate');

app/app/Managers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Managers extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'account_id', 'restaurant_id'
    ];

    public $timestamps = false;

    public function account()
    {
        return $this->hasOne('App\Accounts', 'id', 'account_id');
    }   

    public function restaurant()
    {
        return $this->hasOne('App\Restaurants', 'id', 'restaurant_id');
    }   
}

app/app/Http/Controllers/ManagersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Restaurants;
use App\Accounts;
use App\Roles;
use App\User;
use App\Managers;

use Illuminate\Support\Facades\Hash;

use App\Http\Requests\ManagersRequest;

class ManagersController extends Controller
{

    public function index() 
    {
        // 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $req)
    {
        return view('managers.create', ['restaurants' => Restaurants::all(),
                                        'curr_restaurant' => Restaurants::find($req->input('restaurant')),
                                        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ManagersRequest $request)
    {
        try {
            $user = User::create([
                'name' => $request['name'],
                'email' => $request['email'],
                'password' => Hash::make($request['password']),
            ]);
        } catch (Exception $e) {
            abort(500, 'Ошибка при создании менеджера!');
        }

        try {
            $account = Accounts::create([
                'user_id' => $user->id,
                'role_id' => Roles::where('name', '=', 'manager')->first()->id,
            ]);
        } catch (Exception $e) {
            $user->delete();
            abort(500, 'Ошибка при создании менеджера!');
        }

        try {
            $manager = Managers::create([
                'account_id' => $account->id,
                'restaurant_id' => Restaurants::where('name', '=', $request['restaurant'])->first()->id,
            ]);
        } catch (Exception $e) {
            $user->delete();
            $account->delete();
            abort(500, 'Ошибка при создании менеджера!');
        }

        return redirect(route('managers.show', $manager->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Managers $manager)
    {
        return view('managers.show', ['manager' => $manager]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Managers $manager)
    {
        $manager->account->user->delete();
        $manager->account->delete();
        $manager->delete();
        return redirect(route('restaurants.index'));
    }
}

app/resources/views/managers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1 class="text-center mb-5">Создать менеджера</h1>

    <form method="POST" action="{{ route('managers.store') }}">
        <h3 class="text-center">Данные для авторизации</h3>
        <hr>
        @csrf

        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

            <div class="col-md-6">
                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus placeholder="login">

                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

            <div class="col-md-6">
                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" placeholder="test@mail.ru">

                @error('email')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

            <div class="col-md-6">
                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password" placeholder="password">

                @error('password')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

            <div class="col-md-6">
                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password" placeholder="repeat password">
            </div>
        </div>


        <h3 class="text-center">Ресторан</h3>
        <hr>
        <div class="form-group row">
            <label for="email" class="col-md-4 col-form-label text-md-right">Ресторан</label>

            <div class="col-md-6">
                @if ($curr_restaurant)
                    <input list="restaurantsList"  placeholder="Начните писать или выберите ресторан" id="restaurant" type="text" class="form-control @error('restaurant') is-invalid @enderror" name="restaurant" value="{{ $curr_restaurant->name }}" required  readonly>
                @else
                    <input list="restaurantsList"  placeholder="Начните писать или выберите ресторан" id="restaurant" type="text" class="form-control @error('restaurant') is-invalid @enderror" name="restaurant" value="{{ old('restaurant') }}" required autocomplete="restaurant">
                    <datalist id="restaurantsList">
                        @foreach ($restaurants as $rest)
                        <option>{{$rest->name}}</option>
                        @endforeach
                    </datalist>
                @endif
                @error('restaurant')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    Создать менеджера
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

app/resources/views/managers/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1 class="text-center mb-5">Менеджер "{{$manager->account->user->name}}"</h1>



        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

            <div class="col-md-6">
                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $manager->account->user->name }}" required autocomplete="name" autofocus placeholder="login" disabled>
            </div>
        </div>

        <div class="form-group row">
            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

            <div class="col-md-6">
                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $manager->account->user->email }}" required autocomplete="email" placeholder="test@mail.ru" disabled>
            </div>
        </div>

        <div class="form-group row">
            <span for="email" class="col-md-4  text-md-right">Ресторан</span>
            <span class="col-md-6">
                <a href="{{ route('restaurants.show', $manager->restaurant->id) }}">{{ $manager->restaurant->name }}</a>
            </span>
        </div>
    

        <div class="col-md-6 offset-md-4" style="display: flex; flex-direction: row; justify-content: flex-start;"> 
        
            <form method="GET" action="{{ route('restaurants.index') }}">
                <button type="submit" class="btn btn-primary ">  
                    К ресторанам
                </button>
            </form>


            <form method="POST" action="{{ route('managers.destroy', $manager->id) }}">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-danger">
                            Удалить
                        </button>
                    </div>
                </div>   
            </form>  
        </div>
    
</div>
@endsection