app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('restaurants', 'RestaurantsController')->middleware('can:access,App\Restaurants');

Route::resource('goods', 'GoodsController')->middleware('can:access,App\Goods');

Route::resource('managers', 'ManagersController', ['only' => 
        ['create', 'show', 'store', 'destroy']])
        ->middleware('can:access,App\Restaurants');

Route::resource('categories', 'CategoriesController', ['only' => 
        ['index', 'create', 'store', 'destroy']])
        ->middleware('can:access,App\Restaurants');

Route::resource('couriers', 'CouriersController', ['only' => 
        ['index', 'create', 'store', 'destroy']])
        ->middleware('can:access,App\Restaurants');

Route::get('/', 'FrontendController@restaurants_list')->name('index');
Route::get('/restaurant/{restaurant}', 'FrontendController@restaurant')->name('restaurant');

Route::post('/create-order', 'FrontendController@create_order');
Route::get('/order-confirmation', 'FrontendController@order_confirmation')->name('order_confirmation');
Route::get('/order-cancel/{id}', 'FrontendController@order_cancel')->name('order_cancel');
Route::get('/opened-orders', 'OrdersController@opened_orders_list')->name('opened_orders');

Route::resource('orders', 'OrdersController', ['only' => 
['show', 'store', 'destroy']]);

Route::post('order-completing/{order}', 'OrdersController@complete')->name('order_complete');
Route::post('/courier/attach-order/', 'OrdersController@couriers_attach_order')->name('couriers_attach_order');
Route::get('/courier/orders/', 'OrdersController@couriers_orders_list')->name('couriers_orders_list');

Route::post('/accounts/{id}', 'AccountController@update')->name('accounts_update');

Route::get('rate/{token}', 'RateController@show')->name('rate');
Route::post('rate', 'RateController@store')->name('add_rate');

app/app/Restaurants.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Restaurants extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'address', 'image_id', 'category_id', 'name_lower',
    ];

    public function image()
    {
        return $this->belongsTo('App\Images', 'image_id', 'id');
    }

    public function category()
    {
        return $this->belongsTo('App\Categories', 'category_id', 'id');
    }

    public function rates()
    {
        return $this->hasMany('App\Rate', 'restaurant_id', 'id');
    }

    public function orders()
    {
        return $this->hasMany('App\Orders', 'restaurant_id', 'id');
    }

    public function managers()
    {
        return $this->hasMany('App\Managers', 'restaurant_id', 'id');
    }

    public function goods()
    {
        return $this->hasMany('App\Goods', 'restaurant_id', 'id');
    }
}

app/app/Http/Controllers/RestaurantsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use App\Restaurants;
use App\Images;
use App\Categories;

use App\Http\Requests\RestaurantRequest;
use App\Http\Requests\RestaurantEditRequest;

use Illuminate\Support\Facades\Storage;

class RestaurantsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('restaurants.index', ['restaurants' => Restaurants::orderBy('id', 'asc')->paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categories::all();
        return view('restaurants.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RestaurantRequest $request)
    {
        $category_name = (string)$request->input('category');

        // Создать картинку
        $image = Storage::disk('scaleway')->put('restaurants', $request->file('image'));
        $url = 'https://ngudkov.s3.nl-ams.scw.cloud/' . $image;
        $image_record = Images::create([
            'path' => $url,
        ]);
        
        if(!$image_record) {
            abort(500, 'Ошибка при создании ресторана!');
        }

        // Создать ресторан
        $rest_record = Restaurants::create([
            'name' => $request->input('name'),
            'name_lower' => mb_strtolower($request->input('name')),
            'address' => $request->input('address'),
            'image_id' => (string)$image_record->id,
            'category_id' => (string)Categories::where('name', '=', $category_name)->first()->id,
        ]);

        // TODO: Редирект на создание менеджера
        return redirect(route('restaurants.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Restaurants $restaurant)
    {
        return view('restaurants.show', ['restaurant' => $restaurant]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Restaurants $restaurant)
    {
        return view('restaurants.update', ['restaurant' => $restaurant, 'categories' => $categories = Categories::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RestaurantEditRequest $request, Restaurants $restaurant)
    {
        $params = $request->only('name', 'address', 'category');
        $params['name_lower'] = mb_strtolower($request->input('name'));
        $params['category'] = (string)Categories::where('name', '=', $params['category'])->first()->id;
        
        if ($request->file()) {
            $image = Storage::disk('scaleway')->put('restaurants', $request->file('image'));
            $url = 'https://ngudkov.s3.nl-ams.scw.cloud/' . $image;
            $image_record = Images::create([
                'path' => $url,
            ]);
            
            if(!$image_record) {
                abort(500, 'Ошибка при создании ресторана!');
            }

            $params['image_id'] = $image_record->id;
        }

        $restaurant->update($params);
        return redirect(route('restaurants.show', $restaurant->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Restaurants $restaurant)
    {
        $restaurant->delete();
        return redirect(route('restaurants.index'));
    }
}

app/resources/views/restaurants/create.blade.php
@extends('layouts.app')

@section('content')


<div class="container-fluid">
    <h1 class="text-center mb-3">Добавить Ресторан</h1>
    
        <form method="POST" action="{{url('restaurants')}}" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="row">
                <p for="formFile" class="form-label col-md-6 m-auto">Название:</p>
            </div>
            <div class="mb-3">
                <input class="form-control col-md-6 m-auto @error('name') is-invalid @enderror" type="text" name="name" placeholder="Название" required>
                @error('name')
                    <p class="invalid-feedback text-center" role="alert">
                        <strong>{{ $message }}</strong> 
                    </p>
                @enderror
            </div>
            <div class="row">
                <p for="formFile" class="form-label col-md-6 m-auto">Адрес:</p>
            </div>
            <div class="mb-3">
                <input class="form-control col-md-6 m-auto @error('address') is-invalid @enderror" type="text" name="address" placeholder="Адрес" required>
                @error('address')
                    <p class="invalid-feedback text-center" role="alert">
                        <strong>{{ $message }}</strong> 
                    </p>
                @enderror
            </div>
            <div class="row">
                <div class="col-md-6 m-auto">
                <span for="formFile" class="form-label">Категория:</span>
                <a href="{{route('categories.create')}}">(добавить)</a></div>
            </div>
            <div class="mb-3">
                <select class="form-control col-md-6 m-auto @error('category') is-invalid @enderror" type="text" name="category" required>
                    <option disabled selected>Выберите</option>
                    @foreach($categories as $category)
                        <option>{{ $category->name }}</option>
                    @endforeach
                </select>
                @error('category')
                    <p class="invalid-feedback text-center" role="alert">
                        <strong>{{ $message }}</strong> 
                    </p>
                @enderror
            </div>
            <div class="row">
                <p for="formFile" class="form-label col-md-6 m-auto">Изображение:</p>
            </div>
            <div class="mb-3 row">
                <input class="col-md-6 m-auto @error('image') is-invalid @enderror" type="file" id="formFile" name="image" required>
                @error('image')
                    <p class="invalid-feedback text-center" role="alert">
                        <strong>{{ $message }}</strong> 
                    </p>
                @enderror
            </div>
            <div class="row ml-auto mr-auto">
                <button type="submit" class="btn btn-primary col-md-6 m-auto">Создать</button>
            </div>
        </form>

</div>

@endsection

app/resources/views/restaurants/index.blade.php
@extends('layouts.app')

@section('content')


<div class="container-fluid">
    <h1 class="text-center mb-3">Рестораны</h1>
    <div class="row mb-5 mr-3 ml-3">
        <a class="btn btn-primary col-md-2 d-block m-auto" href="{{route('restaurants.create')}}">Создать</a>
    </div>
    <div style="overflow-x: auto">
        <table class="table">
        <thead class="text-center">
            <tr>
            <th scope="col">id</th>
            <th scope="col">Название</th>
            <th scope="col">Категория</th>
            <th scope="col">Менеджеры</th>
            <th scope="col">Адрес</th>
            <th scope="col">Изображение</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($restaurants as $restaurant)
                <tr>
                    <th class="text-center" scope="row">{{ $restaurant->id }}</th>
                    <td class="text-center"><a href="{{ route('restaurants.show', $restaurant->id) }}">{{ $restaurant->name }}</a></td>
                    <td class="text-center">{{ $restaurant->category->name }}</td>
                    <td class="text-center">
                        <ul style="list-style-type: none; padding: 0">
                            @foreach ($restaurant->managers as $manager)
                                <li><a href="{{route('managers.show', $manager->id)}}">{{$manager->account->user->name}}</a></li>    
                            @endforeach
                            <li><a href="{{route('managers.create', ['restaurant' => $restaurant->id])}}">>>Создать<<</a></li>    
                        </ul>
                    </td>
                    <td class="text-center">{{ $restaurant->address }}</td>
                    <td class="text-center"><a href="{{ $restaurant->image->path }}">Ссылка на изображение</a></td>
                </tr>
            @endforeach
        </tbody>
        </table>
    </div>
    <div class="d-flex mr-3 justify-content-end">
        {{ $restaurants->links("pagination::bootstrap-4") }}
    </div>
</div>

@endsection

app/resources/views/restaurants/show.blade.php
@extends('layouts.app')

@section('content')


<div class="container-fluid">
    <h1 class="text-center mb-3">Ресторан "{{$restaurant->name}}"</h1>
        <div class="row">
            <p for="formFile" class="form-label col-md-6 m-auto">Название:</p>
        </div>
        <div class="mb-3">
            <input disabled class="form-control col-md-6 m-auto" type="text" name="name" placeholder="Название" required value="{{ $restaurant->name }}">
        </div>
        <div class="row">
            <p for="formFile" class="form-label col-md-6 m-auto">Адрес:</p>
        </div>
        <div class="mb-3">
            <input disabled class="form-control col-md-6 m-auto" type="text" name="address" placeholder="Адрес" required value="{{ $restaurant->address }}">
        </div>
        <div class="row">
            <p for="formFile" class="form-label col-md-6 m-auto">Категория:</p>
        </div>
        <div class="mb-3">
            <input disabled class="form-control col-md-6 m-auto" type="text" name="category" required value="{{$restaurant->category->name}}"></input>
        </div>
            
        <img class="rounded mx-auto d-block mb-3" src="{{$restaurant->image->path}}" style="width: 50%">
            
        <div class="col-md-6 m-auto" style="display: flex; flex-direction: row; justify-content: space-between"> 
        
            <form method="POST" action="{{url()->current()}}" id='delForm'>
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
                <div class="row ml-auto mr-auto">
                    <button type="button" class="btn btn-danger m-auto" onclick="if(confirm('Вы уверены, что хотите удалить ресторан {{$restaurant->name}}?')) {delForm.submit();}">Удалить</button>
                </div>
            </form>

            <form>
                <div class="row ml-auto mr-auto">
                    <a class="btn btn-secondary m-auto" href="{{route('managers.create', ['restaurant' => $restaurant->id])}}">Добавить менеджера</a>
                </div>
            </form>

            <form method="get" action="{{url()->current()}}/edit" enctype="multipart/form-data">
                <div class="row ml-auto mr-auto mb-3">
                    <button type="submit" class="btn btn-primary m-auto">Изменить</button>
                </div>
            </form>

            
        </div>

</div>

@endsection

app/resources/views/restaurants/update.blade.php
@extends('layouts.app')

@section('content')


<div class="container-fluid">
    <h1 class="text-center mb-3">Редактировать ресторан "{{$restaurant->name}}"</h1>
    
        <form method="POST" action="{{url('restaurants', $restaurant->id)}}" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="PUT">
            <div class="row">
                <p for="formFile" class="form-label col-md-6 m-auto">Название:</p>
            </div>
            <div class="mb-3">
                <input class="form-control col-md-6 m-auto @error('name') is-invalid @enderror" type="text" name="name" placeholder="Название" required value="{{ $restaurant->name }}">
                @error('name')
                    <p class="invalid-feedback text-center" role="alert">
                        <strong>{{ $message }}</strong> 
                    </p>
                @enderror
            </div>
            <div class="row">
                <p for="formFile" class="form-label col-md-6 m-auto">Адрес:</p>
            </div>
            <div class="mb-3">
                <input class="form-control col-md-6 m-auto @error('address') is-invalid @enderror" type="text" name="address" placeholder="Адрес" required value="{{ $restaurant->address }}">
                @error('address')
                    <p class="invalid-feedback text-center" role="alert">
                        <strong>{{ $message }}</strong> 
                    </p>
                @enderror
            </div>
            <div class="row">
                <div class="col-md-6 m-auto">
                <span for="formFile" class="form-label">Категория:</span>
                <a href="{{route('categories.create')}}">(добавить)</a></div>
            </div>
            <div class="mb-3">
                <select class="form-control col-md-6 m-auto @error('category') is-invalid @enderror" type="text" name="category" required >
                    <option disabled selected>Выберите</option>
                    @foreach($categories as $category)
                        <option @if ($restaurant->category->id === $category->id) selected @endif >{{ $category->name }}</option>
                    @endforeach
                </select>
                @error('category')
                    <p class="invalid-feedback text-center" role="alert">
                        <strong>{{ $message }}</strong> 
                    </p>
                @enderror
            </div>
            <!-- <div class=""> -->
                <img class="rounded mx-auto d-block" src="{{$restaurant->image->path}}" style="width: 50%">
            <!-- </div> -->
            <div class="row">
                <p for="formFile" class="form-label col-md-6 m-auto">Изображение:</p>
            </div>
            <div class="mb-3 row">
                <input class="col-md-6 m-auto @error('image') is-invalid @enderror" type="file" id="formFile" name="image">
                @error('image')
                    <p class="invalid-feedback text-center" role="alert">
                        <strong>{{ $message }}</strong> 
                    </p>
                @enderror
            </div>
            <div class="row ml-auto mr-auto">
                <button type="submit" class="btn btn-primary col-md-6 m-auto">Сохранить</button>
            </div>
        </form>

</div>

@endsection